version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Ho_Chi_Minh
    versioning-strategy: increase
    allow:
      - dependency-type: all
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Ho_Chi_Minh
    labels:
      - dependencies
      - ci
