import { useState } from "react";
import { SafeAreaView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";

export default function App() {
  const [mode, setMode] = useState<"record" | "translate">("record");
  const [recording, setRecording] = useState(false);
  return <SafeAreaView style={styles.safe}><StatusBar barStyle="light-content" /><View style={styles.hero}><Text style={styles.kicker}>KAISER'S MEETING SPACE</Text><Text style={styles.title}>Capture every word.</Text><Text style={styles.subtitle}>Full-fidelity meeting records, wherever work happens.</Text></View><View style={styles.sheet}><Text style={styles.label}>MEETING MODE</Text><View style={styles.modes}><TouchableOpacity style={[styles.mode,mode==="record"&&styles.active]} onPress={()=>setMode("record")}><Text style={styles.modeTitle}>Record</Text><Text style={styles.modeSub}>Audio + full transcript</Text></TouchableOpacity><TouchableOpacity style={[styles.mode,mode==="translate"&&styles.active]} onPress={()=>setMode("translate")}><Text style={styles.modeTitle}>Translate</Text><Text style={styles.modeSub}>Vietnamese ↔ English</Text></TouchableOpacity></View><View style={styles.promise}><Text style={styles.promiseTitle}>Complete by default</Text><Text style={styles.promiseText}>Original audio • Speakers • Timestamps • Full transcript</Text></View><TouchableOpacity style={styles.start} onPress={()=>setRecording(!recording)}><View style={styles.dot}/><Text style={styles.startText}>{recording?"End meeting":"Start meeting"}</Text></TouchableOpacity>{recording&&<Text style={styles.live}>● RECORDING SECURELY</Text>}</View></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#173128"},hero:{padding:28,paddingTop:42,paddingBottom:44},kicker:{color:"#d8ff6a",fontSize:10,letterSpacing:2,fontWeight:"700"},title:{color:"white",fontSize:42,fontWeight:"700",letterSpacing:-1.5,marginTop:12},subtitle:{color:"#b7c3be",fontSize:16,lineHeight:23,marginTop:10},sheet:{flex:1,backgroundColor:"#f5f3ed",borderTopLeftRadius:30,borderTopRightRadius:30,padding:24},label:{fontSize:10,letterSpacing:1.6,color:"#737d78",fontWeight:"700"},modes:{flexDirection:"row",gap:10,marginTop:14},mode:{flex:1,borderWidth:1,borderColor:"#d6d9d5",borderRadius:14,padding:16,backgroundColor:"#fff"},active:{borderWidth:2,borderColor:"#183128",backgroundColor:"#edf4ef"},modeTitle:{fontWeight:"700",fontSize:16,color:"#17201d"},modeSub:{fontSize:12,color:"#707874",marginTop:5,lineHeight:17},promise:{marginTop:24,borderTopWidth:1,borderBottomWidth:1,borderColor:"#deded8",paddingVertical:22},promiseTitle:{fontSize:16,fontWeight:"700",color:"#17201d"},promiseText:{fontSize:12,color:"#737d78",marginTop:7},start:{marginTop:"auto",backgroundColor:"#183128",borderRadius:14,padding:19,alignItems:"center",justifyContent:"center",flexDirection:"row"},dot:{height:9,width:9,borderRadius:5,backgroundColor:"#ff6c5c",marginRight:10},startText:{color:"white",fontWeight:"700",fontSize:16},live:{textAlign:"center",color:"#d14b3f",fontSize:10,letterSpacing:1.4,fontWeight:"700",marginTop:14}});
